apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test06-05-26-1
  namespace: gha-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test06-05-26-1
  template:
    metadata:
      labels:
        app: nginx-test06-05-26-1
    spec:
      containers:
        - name: nginx
          image: nginx:1.25