name: Deploy nginx via Flux (test-cluster)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: v2-deploy-test

    steps:
      - name: Checkout test-githubactions-como-pricer repo
        uses: actions/checkout@v4
        with:
          path: app

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: bhaskar-areti/Istio-helm-migration-k8s-deployments
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops

      - name: Configure git
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Update nginx manifest
        run: |
          cp app/.k8s/nginx.yaml gitops/apps/nginx-test/deployment.yaml

      - name: Commit and push
        run: |
          cd gitops
          git add apps/nginx-test

          if git diff --cached --quiet; then
            echo "No changes detected. Nothing to commit."
            exit 0
          fi

          git commit -m "Deploy nginx to test-cluster via GitHub Actions"
          git push
